apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- argocd-project.yaml
- applications/cluster1-application.yaml
- applications/cluster2-application.yaml
- applications/cluster3-application.yaml
