apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-cluster1
  namespace: argocd
spec:
  project: rabbitmq-clusters
  source:
    repoURL: https://github.com/greplines/rabbitmq_argocd.git
    targetRevision: main
    path: manifests/cluster1
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
